### ISSUE TITLE
Test mockprock on Python 3.11

### ISSUE THREAD

**Issue by feanil** [openedx/mockprock#45]
This repository is a depedency of edx-platform and needs to be upgraded to Python 3.11 before
the Readwood release is cut (mid-April).

- [ ] Requirements are compiled with Python 3.8
- [ ] Tests are run on Python 3.8 and 3.11
- [ ] (Optional) Tests are also run with 3.12 and passing or 3.12 issues are ticketed.
- [ ] Classifiers in setup.py setup.cfg or pyproject.toml indicate Python 3.11 support
- [ ] A new version is release to PyPI
- [ ] A PR is merged to edx-platform to use the new version

**Comment by mariajgrimaldi** [comment]
This repository doesn't have a workflow for Python or unittests, but I'll review it next week to see if I can easily add some.

**Comment by kdmccormick** [comment]
@mariajgrimaldi this is meant to be a development-only tool. Unit tests are always good, but if you have limited time, consider instead removing this from edx-platform's requirement lists. Developers would still be able to install it locally.

**Comment by feanil** [comment]
It looks like this is currently only installed as an [NPM dev dependency](https://github.com/openedx/edx-platform/blob/master/package.json#L89) so we don't need to do anything for the python 3.11 upgrade.
